import './TermUser.scss'
const TermUse = () => {
    return (
        <div className='term-user'>
            <h2>Điều khoản sử dụng của DTube</h2>
            <p>Netflix cung cấp dịch vụ đăng ký được cá nhân hóa, cho phép thành viên truy cập nội dung giải trí (“nội dung trên Netflix”) qua Internet trên một số TV, máy tính và các thiết bị khác có kết nối Internet (“thiết bị tương thích với Netflix”).</p>
            <p>Các Điều khoản sử dụng này điều chỉnh cách thức bạn sử dụng dịch vụ của chúng tôi. Như được sử dụng trong các Điều khoản sử dụng này, các thuật ngữ “dịch vụ của Netflix”, “dịch vụ của chúng tôi” hoặc “dịch vụ” đều có nghĩa là dịch vụ được cá nhân hóa do Netflix cung cấp để khám phá và truy cập nội dung trên Netflix, bao gồm tất cả tính năng và chức năng, đề xuất và đánh giá, các trang web của chúng tôi và giao diện người dùng, cũng như tất cả nội dung và phần mềm liên kết với dịch vụ của chúng tôi. "Bạn" trong các Điều khoản sử dụng này đề cập đến thành viên đã tạo tài khoản Netflix và phương thức thanh toán của thành viên này bị tính phí.</p>
            <p>1. Tư cách thành viên</p>
            <p>1.1. Tư cách thành viên Netflix của bạn sẽ tiếp tục cho đến khi bị chấm dứt. Để sử dụng dịch vụ Netflix, bạn phải có quyền truy cập Internet và một thiết bị tương thích với Netflix, đồng thời cung cấp cho chúng tôi một hay nhiều Phương thức thanh toán. “Phương thức thanh toán” có nghĩa là phương thức thanh toán hiện hành, hợp lệ, được chấp nhận, có thể được cập nhật tùy từng thời điểm và có thể bao gồm phương thức thanh toán qua tài khoản của bạn với bên thứ ba. Trừ trường hợp bạn hủy tư cách thành viên của mình trước ngày thanh toán, bạn cho phép chúng tôi tính phí gói đăng ký cho chu kỳ thanh toán tiếp theo vào Phương thức thanh toán (xem mục “Hủy bỏ” dưới đây).</p>
            <p>1.2. Chúng tôi có thể cung cấp một số gói đăng ký, bao gồm cả gói đăng ký được các bên thứ ba cung cấp đi kèm với các sản phẩm và dịch vụ của riêng họ. Chúng tôi không chịu trách nhiệm đối với các sản phẩm và dịch vụ được cung cấp bởi các bên thứ ba đó. Một số gói đăng ký có thể có các điều kiện và giới hạn khác mà sẽ được thông báo khi bạn đăng ký hoặc trong các thông tin liên lạc khác được gửi đến bạn. Bạn có thể tìm thấy thông tin chi tiết cụ thể về gói đăng ký Netflix của mình bằng cách truy cập trang web netflix.com và nhấp vào liên kết “Tài khoản” ở đầu các trang bên dưới tên hồ sơ của mình.</p>
            <p>2. Ưu đãi khuyến mãi</p>
            <p>Tùy thời điểm, chúng tôi có thể cung cấp các ưu đãi khuyến mãi đặc biệt (như rút thăm trúng thưởng, giảm giá và các ưu đãi khác), gói dịch vụ hoặc tư cách thành viên ("Ưu đãi"). Điều kiện nhận ưu đãi sẽ do Netflix toàn quyền quyết định. Chúng tôi bảo lưu quyền thu hồi Ưu đãi và đóng băng tài khoản của bạn trong trường hợp chúng tôi xác định rằng bạn không đủ điều kiện. Các thành viên của hộ gia đình đã đăng ký hoặc mới đăng ký tài khoản thành viên Netflix có thể không đủ điều kiện nhận một số Ưu đãi chào mừng nhất định. Chúng tôi có thể sử dụng các thông tin như mã thiết bị, phương thức thanh toán hoặc thông tin liên hệ của bạn để xác định điều kiện nhận Ưu đãi. Các yêu cầu về điều kiện nhận ưu đãi cùng các giới hạn và điều kiện khác sẽ được thông báo khi bạn đăng ký nhận Ưu đãi hoặc trong các thông tin liên lạc khác gửi đến bạn.</p>
            <p>3. Thanh toán và Hủy bỏ</p>
            <p>3.1. Chu kỳ thanh toán. Phí đăng ký dịch vụ của Netflix và mọi khoản phí khác mà bạn có thể phải trả liên quan đến việc sử dụng dịch vụ, như thuế và phí giao dịch có thể phát sinh, sẽ được tính vào Phương thức thanh toán vào ngày thanh toán cụ thể được nêu rõ trên trang "Tài khoản". Độ dài của chu kỳ thanh toán sẽ tùy thuộc vào gói đăng ký mà bạn chọn khi đăng ký dịch vụ. Trong một số trường hợp, ngày thanh toán của bạn có thể thay đổi, ví dụ: nếu Phương thức thanh toán của bạn chưa được xử lý thành công, khi bạn thay đổi gói đăng ký hoặc nếu gói đăng ký trả phí của bạn bắt đầu vào một ngày không tồn tại trong một tháng nhất định. Truy cập trang web netflix.com rồi nhấp vào trang "Tài khoản" để xem ngày thanh toán tiếp theo của bạn. Chúng tôi có thể tính phí vào Phương thức thanh toán của bạn trước ngày thanh toán phí của gói đăng ký hoặc các khoản phí liên quan đến dịch vụ thông qua các phương thức khác nhau, bao gồm cả việc tính phí vào Phương thức thanh toán cho thời hạn lên đến khoảng một tháng sử dụng dịch vụ ngay khi bạn đăng ký. Nếu đã đăng ký Netflix bằng tài khoản của bạn với một bên thứ ba làm Phương thức thanh toán, bạn có thể tìm thấy thông tin tính phí cho gói đăng ký Netflix của mình bằng cách truy cập vào tài khoản của bạn với bên thứ ba đó.</p>
            <p>3.2. Các phương thức thanh toán. Để sử dụng dịch vụ Netflix, bạn phải đưa ra một hoặc nhiều Phương thức thanh toán. Bạn cho phép chúng tôi tính phí vào bất kỳ Phương thức thanh toán nào được liên kết với tài khoản của bạn trong trường hợp Phương thức thanh toán chính của bạn bị từ chối hoặc không còn khả dụng đối với chúng tôi để thanh toán phí đăng ký của bạn. Bạn vẫn phải chịu trách nhiệm thanh toán cho bất kỳ khoản tiền chưa thu nào. Nếu khoản thanh toán không được xử lý thành công, do hết hạn, không đủ tiền hoặc các nguyên nhân khác, đồng thời nếu bạn không hủy bỏ tài khoản của mình, chúng tôi có thể tạm dừng quyền truy cập của bạn vào dịch vụ cho đến khi chúng tôi tính phí thành công vào Phương thức thanh toán hợp lệ. Đối với một số Phương thức thanh toán, bạn có thể bị tính phí từ tổ chức phát hành đối với một số khoản phí nhất định, như phí giao dịch nước ngoài hoặc các khoản phí khác liên quan đến việc xử lý Phương thức thanh toán của bạn. Các khoản thuế phí địa phương có thể thay đổi tùy thuộc vào Phương thức thanh toán được sử dụng. Vui lòng kiểm tra với nhà cung cấp dịch vụ Phương thức thanh toán của bạn để biết thêm chi tiết.</p>

        </div>
    )
}

export default TermUse